let camposExportComercial = [{
        id: 'id-nota',
        campo: 'nota.id',
        name: 'id Nota',
        type: 'num',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'ref-nota',
        campo: 'nota.ref',
        name: 'Referencia Nota',
        type: 'text',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-nota',
        campo: 'nota.created_at',
        name: 'Fecha de la Nota',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'estado-nota',
        campo: 'nota.estado',
        name: 'Estado Nota',
        type: 'lista',
        lista: 'lEstadosSol',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'obs-nota',
        campo: 'nota.obs',
        name: 'Observacion Nota',
        type: 'text',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'metodo-nota',
        campo: 'nota.forma_pago_id',
        name: 'Forma de Pago',
        type: 'lista',
        lista: 'lForma_pagos',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'beneficiario',
        campo: 'beneficiarios_id',
        name: 'Beneficiario',
        type: 'lista',
        lista: 'lBeneficiarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'epsa-beneficiario',
        campo: 'beneficiarios_id',
        name: 'Codigo EPSA',
        type: 'lista',
        lista: 'lBeneficiarios:epsa',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: 0,
        orden: 1,
    },
    {
        id: 'id',
        campo: 'id',
        name: 'id Solicitud',
        type: 'num',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-creacion',
        campo: 'created_at',
        name: 'Fecha Creacion',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-creacion',
        campo: 'created_by',
        name: 'Quien lo Creo',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-reviso',
        campo: 'fecha_1',
        name: 'Fecha Revisado',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-revisado',
        campo: 'usuarios_id_1',
        name: 'Quien lo Reviso',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-asigno',
        campo: 'fecha_2',
        name: 'Fecha Asignado',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-asignado',
        campo: 'usuarios_id_2',
        name: 'Quien lo Asigno',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-realizo',
        campo: 'fecha_3',
        name: 'Fecha Realizado',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-realizado',
        campo: 'usuarios_id_3',
        name: 'Quien lo Realizo',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-verificado',
        campo: 'fecha_4',
        name: 'Fecha Verificado',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-verificado',
        campo: 'usuarios_id_4',
        name: 'Quien lo Verifico',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'fecha-autorizado',
        campo: 'fecha_5',
        name: 'Fecha Autorizado',
        type: 'datetime',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'user-autorizado',
        campo: 'usuarios_id_5',
        name: 'Quien lo Autorizo',
        type: 'lista',
        lista: 'lUsuarios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'id-servicio',
        campo: 'servicios_id',
        name: 'Servicio',
        type: 'lista',
        lista: 'lServicios',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'obs-servicio',
        campo: 'sercicios_id',
        name: 'Obs. Servicio',
        type: 'lista',
        lista: 'lServicios:obs',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: 0,
        orden: 1,
    },
    {
        id: 'cant',
        campo: 'cant',
        name: 'Cantidad',
        type: 'num',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: 0,
        orden: 1,
    },
    {
        id: 'estado-solicitud',
        campo: 'estado',
        name: 'Estado Solicitud',
        type: 'lista',
        lista: 'lEstadosSol',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'obs-realizado',
        campo: 'obs',
        name: 'Obs. Realizado',
        type: 'text',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'obs-verificado',
        campo: 'obs_verif',
        name: 'Obs. Verificado',
        type: 'text',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
    {
        id: 'id-eval',
        campo: 'evaluaciones_id',
        name: 'id Evaluacion',
        type: 'num',
        width: '',
        oblig: false,
        selected: true,
        depende: '',
        ligado: '',
        orden: 1,
    },
]
export default camposExportComercial